### ISSUE TITLE
PC Player not login

### ISSUE THREAD

**Issue by ProCOmpTEAM** [BigBrotherTeam/BigBrother#102]
**If I login to my server from PC 1.12.2(other versions send errors 'outdated') to PC(localhost) > I got messages to log and clinet message 'Login timeout'
_MCPE normally working right now!_** 

What about it?

```[23:11:17] [Server thread/INFO]: Loading pocketmine.yml...
[23:11:17] [Server thread/INFO]: Loading server properties...
[23:11:17] [Server thread/INFO]: Selected English (eng) as the base language
[23:11:17] [Server thread/INFO]: Starting Minecraft: PE server version v1.2.7
[23:11:17] [Server thread/WARNING]: Online mode is disabled. The server will not verify that players are authenticated to Xbox Live.
[23:11:17] [Server thread/WARNING]: While this makes it possible to connect without internet access, it also allows hackers to connect with any username they choose.
[23:11:17] [Server thread/WARNING]: To enable authentication, set "xbox-auth" to "true" in server.properties.
[23:11:17] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[23:11:17] [Server thread/INFO]: This server is running PocketMine-MP version 1.7dev-600 "[REDACTED]" (API 3.0.0-ALPHA10)
[23:11:17] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[23:11:17] [Server thread/INFO]: Loading recipes...
[23:11:17] [Server thread/INFO]: Loading resource packs...
[23:11:17] [Server thread/INFO]: Loading DevTools v1.12.8
[23:11:17] [Server thread/INFO]: Enabling DevTools v1.12.8
[23:11:17] [Server thread/INFO]: Loading source plugin BigBrother v1.6.0-beta
[23:11:17] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[23:11:17] [Server thread/INFO]: Enabling BigBrother v1.6.0-beta
[23:11:17] [Server thread/INFO]: [BigBrother] Use openssl as AES encryption engine.
[23:11:17] [Server thread/INFO]: [BigBrother] Use openssl as RSA encryption engine.
[23:11:17] [Server thread/INFO]: [BigBrother] Starting Minecraft: PC server on *:25565 version 1.12.2
[23:11:17] [Server thread/INFO]: Preparing level "world"
[23:11:17] [Server thread/INFO]: Starting GS4 status listener
[23:11:17] [Server thread/INFO]: Setting query port to 19132
[23:11:17] [Server thread/INFO]: Query running on 0.0.0.0:19132
[23:11:17] [Server thread/INFO]: Default game type: Survival Mode
[23:11:17] [Server thread/INFO]: Done (2.643s)! For help, type "help" or "?"
[23:16:45] [Server thread/INFO]: [/127.0.0.1:2686] logged out due to Login timeout
[23:16:48] [Server thread/INFO]: Kirill Poroh[/192.168.100.4:42202] logged in with entity id 1 at (world, 256.5763, 75, 244.634)
[23:16:50] [Server thread/INFO]: Kirill Poroh joined the game
```

_`[23:16:45] [Server thread/INFO]: [/127.0.0.1:2686] logged out due to Login timeout`_

> New version of PM-MP, PHP 7.2, MCPC 1.12.2(tests by 1.11.2, 1.12.2 Forge)

**Comment by ProCOmpTEAM** [comment]
config.yml

> interface: 0.0.0.0
port: 25565
network-compression-threshold: 256
online-mode: false

**Comment by ProCOmpTEAM** [comment]
server.properties
> motd=PocketMine-MP Server
server-port=19132
white-list=off
announce-player-achievements=on
spawn-protection=16
max-players=20
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=ph+7U/s2CK
auto-save=on
view-distance=8
xbox-auth=off

**Comment by ProCOmpTEAM** [comment]
_i have not another plugins except DevTools_

**Comment by ProCOmpTEAM** [comment]
# Connection from other Windows device in local network: so work! But how i create connection from 127.0.0.1?

**Comment by hmy2001** [comment]
Is server connect to network?

**Comment by ProCOmpTEAM** [comment]
@hmy2001 yes, local network have connection to internet

**Comment by Icey-girl** [comment]
I dont have this Isue

**Comment by genboy** [comment]
I cannot login either with 1.12.2, java edition on Mac OS 10.7 - with the original launcher 
(after the last MultiMC update it's launcher didn't work anymore - probably to old mac OS or something - so i do not have a full bug report from clientside)
Server responded:
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused

Hope I can help

**Comment by genboy** [comment]
Hmm, here is my console report on the connection failure
[11:33:59] [Client thread/INFO]: Connecting to 149.202.92.161, 41754
[11:33:59] [Server Connector #2/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: fr2.server.pro/149.202.92.161:41754
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_121]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused
	... 10 more
[11:46:42] [Client thread/INFO]: Connecting to 149.202.92.161, 41754
[11:46:42] [Server Connector #3/ERROR]: Couldn't connect to server
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: fr2.server.pro/149.202.92.161:41754
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_121]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:612) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[netty-all-4.1.9.Final.jar:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) ~[?:1.8.0_121]
Caused by: java.net.ConnectException: Connection refused

**Comment by ProCOmpTEAM** [comment]
my logs is
https://pastebin.com/3NqiwgbW

**Comment by ProCOmpTEAM** [comment]
@genboy @hmy2001 my log have the same error

**Comment by genboy** [comment]
Yes @ProCOmpTEAM indeed, it seems to be a Minecraft/Java bug looking at a [quick search](https://www.google.nl/search?client=firefox-b&dcr=0&ei=wI9fWp7JF83JwQKB9oXoDA&q=minecraft+netty-all-4.1.9.final+connection+problem&oq=minecraft+netty-all-4.1.9.final+connection+problem&gs_l=psy-ab.3..33i160k1.135309.146327.0.146657.30.30.0.0.0.0.140.2214.24j5.29.0....0...1c.1.64.psy-ab..1.17.1414...33i21k1.0.SNdK_To8kG0)

**Comment by ProCOmpTEAM** [comment]
The server was installed by me to VDS _(109.234.37.212)_ and I have this error again. But i gave money for it :( Really problem. Maybe i have bad pc or client?

Another log:
`[22:54:46] [Client thread/INFO]: Connecting to 109.234.37.212, 25565`

**Comment by ProCOmpTEAM** [comment]
Oops!!!!!!! My friend have connection! My PC invalid....

**Comment by ProCOmpTEAM** [comment]
Cooooooooool
# **BigBrother not run width '._.' nicknames!!!!! I was changed my nick and now I have connection!**

NO` **_**` !

**Comment by ProCOmpTEAM** [comment]
We have the bug with nicknames and it is'nt normally

**Comment by genboy** [comment]
Loading terrain! Connection is ok!?! No environmental changes made and now MCPC 1.12.2 works again on PocketMine-MP_1.7dev-525_0ee78d24_API-3.0.0-ALPHA10 

Maybe this is a network/web related bug?

**Comment by hmy2001** [comment]
@genboy changed nicknames?

**Comment by hmy2001** [comment]
It seems that there is an environment that sometimes becomes TimeOut

**Comment by hmy2001** [comment]
But, i don't have an issue

**Comment by ProCOmpTEAM** [comment]
@hmy2001 my friend have this issue but he have not wrong nickname

**Comment by ProCOmpTEAM** [comment]
We was done this actions:
- updated TLauncher to latest version of client
- changed checkbox 'save subversions of game'
- my friend changed nickname from 'egor1245' into 'egor'
and he now have connection. sometimes he gets a close 'login timeout', but he may play with me again

**Comment by genboy** [comment]
@hmy2001 no nicknames used, Pocketmine server.properties xbox-auth=on. Used the original launcher and main account to login.

**Comment by ProCOmpTEAM** [comment]
@genboy Sorry, but any people from Russia have'nt money for licence software

**Comment by ProCOmpTEAM** [comment]
My players got a new IP of my server and have this error "login timout"
![default](https://user-images.githubusercontent.com/24737193/35239017-4ad68bfe-ffc0-11e7-808f-99e1c2791711.png)
Problem....

**Comment by ProCOmpTEAM** [comment]
A lot of people write to me about this error, about 95%. They have TLauncher and have different nicknames. But work only MrPowder, MrPower, and if i change letters then i have this exception. They have clones of log. Only connection and that's all. 

I tried to track the packages read. And i see 0x0 packet(on servers window refresh) and loop... If nickname MrPowder then packets are flying and we can start session and play to game.

@hmy2001 You can guess what's happening?

**Comment by ProCOmpTEAM** [comment]
@hmy2001 I see, that all of my LICENCE players have connetion, but other have only if your nickname have specific combination

**Comment by ProCOmpTEAM** [comment]
@hmy2001 on login(normally nickname, connection exists)
![default](https://user-images.githubusercontent.com/24737193/35569289-e2866498-05dc-11e8-88dd-6a92e8ee4051.png)

**Comment by ProCOmpTEAM** [comment]
@hmy2001 and this log of other Bukkit server
![default](https://user-images.githubusercontent.com/24737193/35569544-69e81864-05dd-11e8-9bc5-8c7197c64c88.png)

**Comment by ProCOmpTEAM** [comment]
@hmy2001 if i create connection from other accounts, i have **Login timeout** and thats all
some players have connection. For example webcam nickname, mrpower....

**Comment by genboy** [comment]
@ProCOmpTEAM, @hmy2001 no luck connecting with any 1.12.2 Java client so far .. 
Online mode is disabled for testing without account, all ended with connection time out;
TLauncher with or without account, original Mojang launcher with account or the MultiMC launcher with or without account..

**Comment by ProCOmpTEAM** [comment]
@genboy @caspervanneck @hmy2001 if i connect from account Kirill_Poroh, i see it in console (empty nick)
![default](https://user-images.githubusercontent.com/24737193/37399782-d1295380-2793-11e8-94a7-07f7016a03d8.png)

**Comment by genboy** [comment]
@ProCOmpTEAM hope i can help testing with this soon, first i have to get a new computer because my MC java hardware engine is a 10 year old powermac which, since last month, can not connect with newer openssl api's anymore, making it pretty useless for online work or gaming. (maybe this is also adding to the bugs?)

**Comment by eternalharvest** [comment]
@genboy 
I'm not sure what is the "openssl" u are talking...
But if u mean php's openssl extension, u can disable the openssl extension.
Because phpseclib has fallback encryption/decryption method which is written in pure PHP.

Anyway Are there anyone who can reproduce this issue?
Or describe what is the exact cause of this problem??

**Comment by genboy** [comment]
@eternalharvest 
I can not test to reproduce yet sorry 
Think this might have something to do with connection en/decryption, looking at the recent global security/encryption changes and the strange nickname bug/hack/workaround to get connection. But I'm still learning about encryption, ssl etc..

The openssl protocol is used both clientside and serverside to secure connections. Github and most other software giants have deprecated the (very) old openssl protocol version since februari 2018. Older computers like a 2008 powermac are not able to update to the new protocol version due to too many old security risks.

**Comment by eternalharvest** [comment]
@genboy 

I think we need to break down this issue into more simple issue.

BigBrother use openssl two way, one is phpseclib which use openssl extension of php, and the another one is implicit url access such as authentication or retrieve profile data from mojang server.
Please refer to the following codes...

https://github.com/BigBrotherTeam/BigBrother/blob/888068ede1a7ae265671a60403c345a6f706b14a/src/shoghicp/BigBrother/DesktopPlayer.php#L616

I'll write some patch which dump environment specific prerequisite condition into debug log.

**Comment by genboy** [comment]
@eternalharvest @hmy2001  @ProCOmpTEAM 

With the [mayfixnicknameproblem-code](https://github.com/eternalharvest/BigBrother/tree/hotfix/may_fix_nickname_problem) I joined my server :) 
and then the main threat crashed.. [dump here](https://gist.github.com/genboy/0fae308e25232e255ecab1dc727c0cab#file-crashdump_1_bigbrother)

The recent [master](https://github.com/BigBrotherTeam/BigBrother) code worked also, i was connected for over 2 min. before an error occured;
 internel exception: java.io.IOException: Connection reset by peer
After refresh and trying to connect again:
2018-04-09 [18:26:25][Server thread/EMERGENCY]: [ServerThread #115462565525248] ServerThread crashed! [console dump here](https://gist.github.com/genboy/dc810b332ce942bfcb88535b60129b31#file-gistfile1-txt)

2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] OS: Linux fr26.server.pro 3.14.32-xxxx-grs-ipv6-64 #6 SMP Wed Jan 20 17:52:44 CET 2016 x86_64
2018-04-09 [19:07:23] Server thread/INFO]: [BigBrother] PHP version: 7.2.0RC4 
2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] PMMP version: 1.7dev-916 [REDACTED] 2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] PMMP Server version: v1.2.13
2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] PMMP API version: 3.0.0-ALPHA11 2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] Use openssl as AES encryption engine. 2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] Use openssl as RSA encryption engine. 2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] OpenSSL Library version: OpenSSL 1.1.0f 25 May 2017 
2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] OpenSSL Header version: OpenSSL 1.1.0f 25 May 2017
2018-04-09 [19:07:23] [Server thread/INFO]: [BigBrother] Starting Minecraft: PC server on 149.202.83.16:40027 version 1.12.2

 All with my old powermac, TLauncher and online mode false :)

**Comment by eternalharvest** [comment]
@genboy 
Thank u for reporting detailed information!
But I can’t reproduce the problem u mentioned.

According to ur log, It seems login sequence itself is not a problem…
It seems `SpawnExperienceOrbPacket#encode()` is called with invalid `count` member variable which is comming from nametag.

https://github.com/BigBrotherTeam/BigBrother/blob/ff20407c6bbead3f8ad73b9c9c3cbb8f40f87fb1/src/shoghicp/BigBrother/network/Translator.php#L1181

But it looks already fixed by the commit 83e6700f172f8f471c74ccbace560b49572463c1 on latest master branch thanks to @hmy2001.
If u have still this problem with latest master branch, please make new issue for this.

In this case, I think nickname (username) is not a cause and it seems there is no login problem but I rebased my branch ‘hotfix/may_fix_nickname_problem’ onto latest master branch.
I would be happy if this change-set helps ur work on debugging.

**Comment by eternalharvest** [comment]
I experimentally add the code `sleep(120)` into `DesktopPlayer#bigBrother_authenticate()` method, and it seems the threshold of timeout of MCPC (Java) is about 30 seconds…

**Comment by genboy** [comment]
@eternalharvest 
Thank U 2, revived my Mac for gaming again :) If needed i'll take my issue elsewhere, this long one can close i think

**Comment by eternalharvest** [comment]
Sorry, this issue might not be fixed yet...
But we couldn't find out the exact cause of this issue and the step how to reproduce.
And this thread is too long and heavy because of any screenshot, code snippets, and so on...

And I think this issue is unclear because there are some reports that prerequisite conditions might not be same as that of original issue.
Please create new issue using template and report the bug with prerequisite conditions when u find a new bug.

@ProCOmpTEAM @genboy
Thank u for reporting the issue!
I close this issue, but please feel free to report any issue even if the issue is difficult to reproduce it.

Thanks
